---
- name: install prerequisites
  apt:
    name:
      - git
      - python3-pip
      - sshpass
      - pigz
    update_cache: yes

- name: install pip packages
  environment:
    LANG: "C.UTF-8"
    LC_ALL: "C.UTF-8"
  pip:
    name:
      - ansible
      - docker-compose
